updated spring version
awslabs/aws-serverless-java-container pull request #381
Opened 2020-09-21 05:54 UTC by jabhijeet

*Issue #, if available:*

*Description of changes:*

By submitting this pull request

- [ ] I confirm that my contribution is made under the terms of the Apache 2.0 license.
- [ ] I confirm that I've made a best effort attempt to update all relevant documentation.

2020-09-23 17:48 UTC, sapessi requested changes
Can you remove the additional newline from the pom file? Otherwise looks good.

2020-09-23 17:48 UTC, sapessi commented on aws-serverless-java-container-springboot2/pom.xml
> +
Why the newline here?

2020-09-24 01:10 UTC, jabhijeet commented on aws-serverless-java-container-springboot2/pom.xml
> +
sorry for that... removed it now

2020-09-24 17:14 UTC, sapessi approved these changes

2020-09-24 17:14 UTC, merged