Make compatible with Jakarta namespace
awslabs/aws-serverless-java-container pull request #478
Opened 2022-09-30 13:11 UTC by farazhv

*Issue #, if available:*

Multipart form upload is not supported

*Description of changes:*
Compatible with Jakarta namespace

By submitting this pull request

- [ ] I confirm that my contribution is made under the terms of the Apache 2.0 license.
- [ ] I confirm that I've made a best effort attempt to update all relevant documentation.

2022-09-30 13:11 UTC, farazhv commented
With reference to issue: https://github.com/awslabs/aws-serverless-java-container/issues/477

2022-09-30 13:24 UTC, deki requested changes
Thanks for the work you put into it. 

There are a lot of whitespace changes make it difficult to sort out the real changes but I already saw some places that look like a merge error to me. Would you mind double checking?

I'll probably merge this to a different branch, so another volunteer (or myself) can work on the Multipart stuff. Spring 6 and Spring Boot 3 will be released soon and I will include it along with this change as well.

2022-09-30 13:24 UTC, deki commented on aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/model/AwsProxyRequest.java
> -    private Map<String, String> queryStringParameters;
looks like a merge issue to me, this shouldn't be removed

2022-09-30 13:24 UTC, deki commented on aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/model/AwsProxyRequest.java
> -    private SingleValueHeaders headers;
looks like a merge issue to me, this shouldn't be removed

2022-09-30 13:24 UTC, deki commented on aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/model/SingleValueHeaders.java
> -/*
looks like a merge issue to me, this shouldn't be removed

2022-10-14 08:19 UTC, farazhv commented
Thank you for pointing this out. 
 
Since this branch was based on an earlier commit of the master branch, it didn’t include the most recent change. My last commit to this branch addresses this and resolves the merge conflict. 

We are using the submitted code in a lambda to host our webserver – so it is working for us.

2023-01-02 15:28 UTC, tntsoft commented
@deki Is there any timeline in place to get these changes sorted, merged and released? Got a Spring Boot 3 application which I'm planning to move to AWS Lambda, so am wondering if I need to go and tinker it myself, or put it on the back burner until the new release.

2023-04-25 15:00 UTC, deki commented
Hi folks,
sorry for the delay but we finally made the changes in the main branch.

@farazhv while comparing with your PR, I notice a NullInputStream and some changes related to binary reading? Is that needed? Could you please test the main branch if it's working for you?

2023-04-25 15:29 UTC, farazhv commented
@deki sure we will test the main branch as soon as we can

2023-05-19 15:42 UTC, closed without merging

2023-05-24 20:10 UTC, farazhv commented
@deki we aren't blocked by this so we won't be able to test it for the time being