Add implementation of delegating RequestStreamHandler
awslabs/aws-serverless-java-container pull request #603
Opened 2023-06-28 16:17 UTC by olegz

This new handler delegates to spring-cloud-function-serverless-web module which is managed by Spring team

This PR is a substitution for the one I canceled https://github.com/awslabs/aws-serverless-java-container/pull/578 and is better in a way that it requires user to opt-in to use this handler. The current AWS code is not touched providing a very smooth and safe transition.
I will also be publishing a sample on how to use it

By submitting this pull request

- [x] I confirm that my contribution is made under the terms of the Apache 2.0 license.
- [x] I confirm that I've made a best effort attempt to update all relevant documentation.

2023-06-29 06:46 UTC, mbfreder commented
There are failing tests. @olegz Could you please take a look?

2023-06-30 15:43 UTC, sapessi commented on samples/springboot3/alt-pet-store/template.yml
> +Resources:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

StageName contains invalid characters (Pattern: ^[a-zA-Z0-9-_]+$) at Resources/ServerlessHttpApiApiGatewayDefaultStage/Properties/StageName

2023-07-03 17:05 UTC, mbfreder approved these changes

2023-07-03 20:57 UTC, valerena requested changes
It looks good other than the tabs that should be spaces.

2023-07-03 20:57 UTC, valerena commented on aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/model/AwsProxyRequest.java
> +	private String resource;
Tab

2023-07-03 20:57 UTC, valerena commented on aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/model/AwsProxyRequest.java
> +	}
Tabs

2023-07-03 20:57 UTC, valerena commented on aws-serverless-java-container-springboot3/pom.xml
> +	</repositories>
Tabs

2023-07-03 20:57 UTC, valerena commented on aws-serverless-java-container-springboot3/src/main/java/com/amazonaws/serverless/proxy/spring/SpringDelegatingLambdaContainerHandler.java
> +	private final Class<?>[] startupClasses;
Most of this file has tabs instead of spaces

2023-07-03 20:57 UTC, valerena commented on aws-serverless-java-container-springboot3/src/test/java/com/amazonaws/serverless/proxy/spring/SpringDelegatingLambdaContainerHandlerTests.java
> +	private static String API_GATEWAY_EVENT = "{\n"
This whole file has tabs instead of spaces.

2023-07-03 20:57 UTC, valerena commented on samples/springboot3/alt-pet-store/src/main/java/com/amazonaws/serverless/sample/springboot3/Application.java
> +    	return new CognitoIdentityFilter();
There's a single tab here (4 spaces followed by a tab)

2023-07-05 16:13 UTC, valerena approved these changes

2023-07-06 08:49 UTC, merged